name: SPR tarkistus

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 1 * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas openpyxl

      - name: Show files
        run: |
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la

      - name: Run script
        run: python spr_tarkistus.py

      - name: Upload report
        uses: actions/upload-artifact@v7
        with:
          name: osasto-raportti
          path: "*.xlsx"
